name: CI

on:
  push:
    branches: [dev, qa, uat, preprod, main]
  pull_request:
    branches: [dev, qa, uat, preprod, main]

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: app-service/Dockerfile

  build-test:
    runs-on: ubuntu-latest
    needs: dockerfile-lint

    defaults:
      run:
        working-directory: app-service

    steps:
      - name: Checkout application
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build and test
        run: make build && make test

  deploy-dev:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    uses: xiao199963-creator/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: dev
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  deploy-qa:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/qa'
    uses: xiao199963-creator/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: qa
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  deploy-uat:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/uat'
    uses: xiao199963-creator/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: uat
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  deploy-preprod:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/preprod'
    uses: xiao199963-creator/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: preprod
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  deploy-prod:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: xiao199963-creator/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: prod
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}